### ISSUE TITLE
Set etcd mode as proxy from the 4th machine and above

### ISSUE THREAD

**Issue by xh3b4sd** [giantswarm/mayu#10] opened 2016-02-03 14:14 UTC
_From @crisidev on December 2, 2015 10:42_

When spawning virtual machines (vbox / fusion) the first 3 are hitting discovery.etcd.io and setting up the quorum. Usually the 4th machines boot up ~ 30 seconds after and it tries (I guess because of timing) to become part of the quorum. Doing this, etcd will write the folder /var/lib/etcd2/member and will not start in proxy mode. Every time etcd service restarts, discovery.etcd.io will tell it the cluster is full and will continue to fail. I spoke with @htr about this and he told me we could fix this in bootxe setting the "role" of etcd as proxy from the 4th machine and above.

Thoughts?

_Copied from original issue: giantswarm/bootxe#51_

**Comment by teemow** [comment] 2016-07-01 20:06
I can't reproduce this anymore. Using etcd 2.3.1. Closing.

**Closed by teemow** 2016-07-01 20:06 UTC
Labels: kind/bug, priority/p1
